### ISSUE TITLE
Websocket response

### ISSUE THREAD

**Issue by christophsaile** [bykof/cordova-plugin-webserver#63]
Hello,

I am currently struggeling to use this plugin to establish a websocket connection.
My goal is to send a ws request to the local server and create a connection.
If I use the response header from your example I get the following error:

![90226636-9132ec80-de13-11ea-91d5-4f4ead94e878](https://user-images.githubusercontent.com/54807480/93184474-94840580-f73c-11ea-8ddb-310e328d3911.png)

I have already tried to change the status of the response header to "101 Switching Protocols" but that did not work for me.

![90952740-6f1a1980-e466-11ea-868f-9383775bf42e](https://user-images.githubusercontent.com/54807480/93184774-f2185200-f73c-11ea-9227-0c21243ec4cc.png)

Do you have any idea if its possible to create a websocket connection between two devices with your plugin?

thanks in advance,
Christoph

**Comment by bykof** [comment]
Hi Christoph, it's poorly not possible to create a websocket connection because the webserver needs to open up a http socket and hold it until one of the participants close it. If you send a request to the plugin, the request will be send to the JavaScript runtime, after the request has been sent, the socket is already closed and therefore it's not possible to establish a websocket connection. sorry for that.

**Comment by christophsaile** [comment]
Ahh ok makes sense.
Thanks for your fast response.
