### ISSUE TITLE
Can you provide a license file please?

### ISSUE THREAD

**Issue by zangzimi** [bykof/cordova-plugin-webserver#73]
@bykof Thanks for making this library. Can you please provide a license file? Or should a make a PR to do so?

**Comment by saschal-j5int** [comment]
Hi @bykof, we need that too.  Also since you use two other libraries in it. Could we please have confirmation that you have not reused any third-party code and just reference these libraries in your code? So we have confirmation we can use this library ander the Apache-2.0 license. 

If you have reused third-party code. You could add the BSD clauses as NOTICE.md files.

That would incredible helpful!

Many thanks

**Comment by zangzimi** [comment]
The license is added. Thanks so much!
